In [5]:
# Program to draw edges and show transition probability between hidden states
# AIM = to draw network between different states
import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

# create state space and initial state probabilities

states = ['sleeping', 'eating', 'Reading']  # given Hidden state 
pi = [0.35, 0.45, 0.2] # given Intial probability 
state_space = pd.Series(pi, index=states, name='states')
print(state_space)
print(state_space.sum())


# create transition matrix
# equals transition probability matrix of changing states given a state
# matrix is size (M x M) where M is number of states

q_df = pd.DataFrame(columns=states, index=states)
q_df.loc[states[0]] = [0.4, 0.2, 0.4]
q_df.loc[states[1]] = [0.45, 0.45, 0.1]
q_df.loc[states[2]] = [0.45, 0.25, .3]

print(q_df)

q = q_df.values # values of transition probability
print('\n', q, q.shape, '\n')
print(q_df.sum(axis=1))


from pprint import pprint 
# create a function that maps transition probability dataframe 
# to markov edges and weights

def _get_markov_edges(Q):
    edges = {} # empty tuple
    for col in Q.columns:
        for idx in Q.index:
            edges[(idx,col)] = Q.loc[idx,col]
    return edges

edges_wts = _get_markov_edges(q_df)
pprint(edges_wts)


# create graph object
G = nx.MultiDiGraph()

# nodes correspond to states
G.add_nodes_from(states)
print(f'Nodes:\n{G.nodes()}\n')

# edges represent transition probabilities
for k, v in edges_wts.items():
    tmp_origin, tmp_destination = k[0], k[1]
    G.add_edge(tmp_origin, tmp_destination, weight=v, label=v)
print(f'Edges:')
pprint(G.edges(data=True))   

sleeping    0.35
eating      0.45
Reading     0.20
Name: states, dtype: float64
1.0
         sleeping eating Reading
sleeping      0.4    0.2     0.4
eating       0.45   0.45     0.1
Reading      0.45   0.25     0.3

 [[0.4 0.2 0.4]
 [0.45 0.45 0.1]
 [0.45 0.25 0.3]] (3, 3) 

sleeping    1.0
eating      1.0
Reading     1.0
dtype: float64
{('Reading', 'Reading'): 0.3,
 ('Reading', 'eating'): 0.25,
 ('Reading', 'sleeping'): 0.45,
 ('eating', 'Reading'): 0.1,
 ('eating', 'eating'): 0.45,
 ('eating', 'sleeping'): 0.45,
 ('sleeping', 'Reading'): 0.4,
 ('sleeping', 'eating'): 0.2,
 ('sleeping', 'sleeping'): 0.4}
Nodes:
['sleeping', 'eating', 'Reading']

Edges:
OutMultiEdgeDataView([('sleeping', 'sleeping', {'weight': 0.4, 'label': 0.4}), ('sleeping', 'eating', {'weight': 0.2, 'label': 0.2}), ('sleeping', 'Reading', {'weight': 0.4, 'label': 0.4}), ('eating', 'sleeping', {'weight': 0.45, 'label': 0.45}), ('eating', 'eating', {'weight': 0.45, 'label': 0.45}), ('eating', 'Reading', {'weight': 0.

In [7]:
G.add_nodes_from(states)

In [8]:
print(f'Nodes:\n{G.nodes()}\n')

Nodes:
['sleeping', 'eating', 'Reading']

